// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: board.proto

package board

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resource int32

const (
	Resource_ANY    Resource = 0
	Resource_DESERT Resource = 1
	Resource_LUMBER Resource = 2
	Resource_BRICK  Resource = 3
	Resource_WOOL   Resource = 4
	Resource_GRAIN  Resource = 5
	Resource_ORE    Resource = 6
)

// Enum value maps for Resource.
var (
	Resource_name = map[int32]string{
		0: "ANY",
		1: "DESERT",
		2: "LUMBER",
		3: "BRICK",
		4: "WOOL",
		5: "GRAIN",
		6: "ORE",
	}
	Resource_value = map[string]int32{
		"ANY":    0,
		"DESERT": 1,
		"LUMBER": 2,
		"BRICK":  3,
		"WOOL":   4,
		"GRAIN":  5,
		"ORE":    6,
	}
)

func (x Resource) Enum() *Resource {
	p := new(Resource)
	*p = x
	return p
}

func (x Resource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Resource) Descriptor() protoreflect.EnumDescriptor {
	return file_board_proto_enumTypes[0].Descriptor()
}

func (Resource) Type() protoreflect.EnumType {
	return &file_board_proto_enumTypes[0]
}

func (x Resource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Resource.Descriptor instead.
func (Resource) EnumDescriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{0}
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left        *Edge      `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right       *Edge      `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	Up          *Edge      `protobuf:"bytes,3,opt,name=up,proto3" json:"up,omitempty"`
	Down        *Edge      `protobuf:"bytes,4,opt,name=down,proto3" json:"down,omitempty"`
	Progression int32      `protobuf:"varint,5,opt,name=progression,proto3" json:"progression,omitempty"`
	Player      int32      `protobuf:"varint,6,opt,name=player,proto3" json:"player,omitempty"`
	Port        *TradePort `protobuf:"bytes,7,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_board_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetLeft() *Edge {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *Point) GetRight() *Edge {
	if x != nil {
		return x.Right
	}
	return nil
}

func (x *Point) GetUp() *Edge {
	if x != nil {
		return x.Up
	}
	return nil
}

func (x *Point) GetDown() *Edge {
	if x != nil {
		return x.Down
	}
	return nil
}

func (x *Point) GetProgression() int32 {
	if x != nil {
		return x.Progression
	}
	return 0
}

func (x *Point) GetPlayer() int32 {
	if x != nil {
		return x.Player
	}
	return 0
}

func (x *Point) GetPort() *TradePort {
	if x != nil {
		return x.Port
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start *Point `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   *Point `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Road  int32  `protobuf:"varint,3,opt,name=road,proto3" json:"road,omitempty"`
}

func (x *Edge) Reset() {
	*x = Edge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_board_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{1}
}

func (x *Edge) GetStart() *Point {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Edge) GetEnd() *Point {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *Edge) GetRoad() int32 {
	if x != nil {
		return x.Road
	}
	return 0
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Resource Resource `protobuf:"varint,2,opt,name=resource,proto3,enum=df.Resource" json:"resource,omitempty"`
	Points   []*Point `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	Thief    bool     `protobuf:"varint,4,opt,name=thief,proto3" json:"thief,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_board_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Block) GetResource() Resource {
	if x != nil {
		return x.Resource
	}
	return Resource_ANY
}

func (x *Block) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *Block) GetThief() bool {
	if x != nil {
		return x.Thief
	}
	return false
}

type TradePort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource Resource `protobuf:"varint,1,opt,name=resource,proto3,enum=df.Resource" json:"resource,omitempty"`
	Price    int32    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *TradePort) Reset() {
	*x = TradePort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_board_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradePort) ProtoMessage() {}

func (x *TradePort) ProtoReflect() protoreflect.Message {
	mi := &file_board_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradePort.ProtoReflect.Descriptor instead.
func (*TradePort) Descriptor() ([]byte, []int) {
	return file_board_proto_rawDescGZIP(), []int{3}
}

func (x *TradePort) GetResource() Resource {
	if x != nil {
		return x.Resource
	}
	return Resource_ANY
}

func (x *TradePort) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_board_proto protoreflect.FileDescriptor

var file_board_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x64,
	0x66, 0x22, 0xda, 0x01, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x6c,
	0x65, 0x66, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x64, 0x66, 0x2e, 0x45,
	0x64, 0x67, 0x65, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x1e, 0x0a, 0x05, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x64, 0x66, 0x2e, 0x45, 0x64,
	0x67, 0x65, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x18, 0x0a, 0x02, 0x75, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x64, 0x66, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x52,
	0x02, 0x75, 0x70, 0x12, 0x1c, 0x0a, 0x04, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x64, 0x66, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x52, 0x04, 0x64, 0x6f, 0x77,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x66, 0x2e, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x58,
	0x0a, 0x04, 0x45, 0x64, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64, 0x66, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64, 0x66, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x03, 0x65, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x61, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x05, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x64, 0x66, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x21, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64, 0x66, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x69, 0x65, 0x66, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x74, 0x68, 0x69, 0x65, 0x66, 0x22, 0x4b, 0x0a, 0x09, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x64, 0x66, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2a, 0x54, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4e, 0x59, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x44, 0x45, 0x53, 0x45, 0x52, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x55, 0x4d,
	0x42, 0x45, 0x52, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x52, 0x49, 0x43, 0x4b, 0x10, 0x03,
	0x12, 0x08, 0x0a, 0x04, 0x57, 0x4f, 0x4f, 0x4c, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x52,
	0x41, 0x49, 0x4e, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x52, 0x45, 0x10, 0x06, 0x42, 0x0a,
	0x5a, 0x08, 0x64, 0x66, 0x2f, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_board_proto_rawDescOnce sync.Once
	file_board_proto_rawDescData = file_board_proto_rawDesc
)

func file_board_proto_rawDescGZIP() []byte {
	file_board_proto_rawDescOnce.Do(func() {
		file_board_proto_rawDescData = protoimpl.X.CompressGZIP(file_board_proto_rawDescData)
	})
	return file_board_proto_rawDescData
}

var file_board_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_board_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_board_proto_goTypes = []interface{}{
	(Resource)(0),     // 0: df.Resource
	(*Point)(nil),     // 1: df.Point
	(*Edge)(nil),      // 2: df.Edge
	(*Block)(nil),     // 3: df.Block
	(*TradePort)(nil), // 4: df.TradePort
}
var file_board_proto_depIdxs = []int32{
	2,  // 0: df.Point.left:type_name -> df.Edge
	2,  // 1: df.Point.right:type_name -> df.Edge
	2,  // 2: df.Point.up:type_name -> df.Edge
	2,  // 3: df.Point.down:type_name -> df.Edge
	4,  // 4: df.Point.port:type_name -> df.TradePort
	1,  // 5: df.Edge.start:type_name -> df.Point
	1,  // 6: df.Edge.end:type_name -> df.Point
	0,  // 7: df.Block.resource:type_name -> df.Resource
	1,  // 8: df.Block.points:type_name -> df.Point
	0,  // 9: df.TradePort.resource:type_name -> df.Resource
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_board_proto_init() }
func file_board_proto_init() {
	if File_board_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_board_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_board_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Edge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_board_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_board_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradePort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_board_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_board_proto_goTypes,
		DependencyIndexes: file_board_proto_depIdxs,
		EnumInfos:         file_board_proto_enumTypes,
		MessageInfos:      file_board_proto_msgTypes,
	}.Build()
	File_board_proto = out.File
	file_board_proto_rawDesc = nil
	file_board_proto_goTypes = nil
	file_board_proto_depIdxs = nil
}
