// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: settlers.proto

package settlers

import (
	context "context"
	grpc "google.golang.org/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_settlers_proto protoreflect.FileDescriptor

var file_settlers_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x73, 0x72, 0x76, 0x63, 0x32, 0x0a, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65,
	0x72, 0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x73, 0x72, 0x76, 0x63, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x6c,
	0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_settlers_proto_goTypes = []interface{}{}
var file_settlers_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_settlers_proto_init() }
func file_settlers_proto_init() {
	if File_settlers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_settlers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settlers_proto_goTypes,
		DependencyIndexes: file_settlers_proto_depIdxs,
	}.Build()
	File_settlers_proto = out.File
	file_settlers_proto_rawDesc = nil
	file_settlers_proto_goTypes = nil
	file_settlers_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SettlersClient is the client API for Settlers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SettlersClient interface {
}

type settlersClient struct {
	cc grpc.ClientConnInterface
}

func NewSettlersClient(cc grpc.ClientConnInterface) SettlersClient {
	return &settlersClient{cc}
}

// SettlersServer is the server API for Settlers service.
type SettlersServer interface {
}

// UnimplementedSettlersServer can be embedded to have forward compatible implementations.
type UnimplementedSettlersServer struct {
}

func RegisterSettlersServer(s *grpc.Server, srv SettlersServer) {
	s.RegisterService(&_Settlers_serviceDesc, srv)
}

var _Settlers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "srvc.Settlers",
	HandlerType: (*SettlersServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "settlers.proto",
}
