// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: settlers.proto

package settlers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DiceRequest) Reset() {
	*x = DiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settlers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiceRequest) ProtoMessage() {}

func (x *DiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiceRequest.ProtoReflect.Descriptor instead.
func (*DiceRequest) Descriptor() ([]byte, []int) {
	return file_settlers_proto_rawDescGZIP(), []int{0}
}

type DiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dice1 int32 `protobuf:"varint,1,opt,name=dice1,proto3" json:"dice1,omitempty"`
	Dice2 int32 `protobuf:"varint,2,opt,name=dice2,proto3" json:"dice2,omitempty"`
}

func (x *DiceResponse) Reset() {
	*x = DiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settlers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiceResponse) ProtoMessage() {}

func (x *DiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiceResponse.ProtoReflect.Descriptor instead.
func (*DiceResponse) Descriptor() ([]byte, []int) {
	return file_settlers_proto_rawDescGZIP(), []int{1}
}

func (x *DiceResponse) GetDice1() int32 {
	if x != nil {
		return x.Dice1
	}
	return 0
}

func (x *DiceResponse) GetDice2() int32 {
	if x != nil {
		return x.Dice2
	}
	return 0
}

var File_settlers_proto protoreflect.FileDescriptor

var file_settlers_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x44, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x0c, 0x44, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x69, 0x63, 0x65, 0x31, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x69, 0x63, 0x65, 0x31, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x69, 0x63, 0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x69, 0x63,
	0x65, 0x32, 0x32, 0x41, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x72, 0x73, 0x12, 0x35,
	0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x6c, 0x44, 0x69, 0x63, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x65, 0x74, 0x74, 0x6c, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_settlers_proto_rawDescOnce sync.Once
	file_settlers_proto_rawDescData = file_settlers_proto_rawDesc
)

func file_settlers_proto_rawDescGZIP() []byte {
	file_settlers_proto_rawDescOnce.Do(func() {
		file_settlers_proto_rawDescData = protoimpl.X.CompressGZIP(file_settlers_proto_rawDescData)
	})
	return file_settlers_proto_rawDescData
}

var file_settlers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_settlers_proto_goTypes = []interface{}{
	(*DiceRequest)(nil),  // 0: proto.DiceRequest
	(*DiceResponse)(nil), // 1: proto.DiceResponse
}
var file_settlers_proto_depIdxs = []int32{
	0, // 0: proto.Settlers.rollDice:input_type -> proto.DiceRequest
	1, // 1: proto.Settlers.rollDice:output_type -> proto.DiceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_settlers_proto_init() }
func file_settlers_proto_init() {
	if File_settlers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_settlers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_settlers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_settlers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settlers_proto_goTypes,
		DependencyIndexes: file_settlers_proto_depIdxs,
		MessageInfos:      file_settlers_proto_msgTypes,
	}.Build()
	File_settlers_proto = out.File
	file_settlers_proto_rawDesc = nil
	file_settlers_proto_goTypes = nil
	file_settlers_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SettlersClient is the client API for Settlers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SettlersClient interface {
	RollDice(ctx context.Context, in *DiceRequest, opts ...grpc.CallOption) (*DiceResponse, error)
}

type settlersClient struct {
	cc grpc.ClientConnInterface
}

func NewSettlersClient(cc grpc.ClientConnInterface) SettlersClient {
	return &settlersClient{cc}
}

func (c *settlersClient) RollDice(ctx context.Context, in *DiceRequest, opts ...grpc.CallOption) (*DiceResponse, error) {
	out := new(DiceResponse)
	err := c.cc.Invoke(ctx, "/proto.Settlers/rollDice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettlersServer is the server API for Settlers service.
type SettlersServer interface {
	RollDice(context.Context, *DiceRequest) (*DiceResponse, error)
}

// UnimplementedSettlersServer can be embedded to have forward compatible implementations.
type UnimplementedSettlersServer struct {
}

func (*UnimplementedSettlersServer) RollDice(context.Context, *DiceRequest) (*DiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollDice not implemented")
}

func RegisterSettlersServer(s *grpc.Server, srv SettlersServer) {
	s.RegisterService(&_Settlers_serviceDesc, srv)
}

func _Settlers_RollDice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlersServer).RollDice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Settlers/RollDice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlersServer).RollDice(ctx, req.(*DiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Settlers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Settlers",
	HandlerType: (*SettlersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "rollDice",
			Handler:    _Settlers_RollDice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "settlers.proto",
}
